logging:
  level:
    ROOT: INFO
    org:
      springframework:
        cloud:
          stream: DEBUG

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: sales-service
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:venda_db2
    username: sa
    password:
    driverClassName: org.h2.Driver
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    time-between-eviction-runs-millis: 90000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: 'update'

  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    max-retry: 3
    replications: 3
    default-partitions: 3
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: sales-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      sales:
        name: sales
        partitions: 3
      sales-dlt:
        name: sales.DLT
      sales-batch:
        name: sales-batch
      sales-batch-dtl:
        name: sales-batch.DLT
app:

---

spring:
  config:
    activate:
      on-profile: pg
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_01?currentSchema=sales
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 1000
        order_inserts: true
    hibernate:
      dialect:  org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: 'none'


